name: Parallel Number Printing

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  print_number:
    runs-on: arc-runner-set
    strategy:
      matrix:
        number: [1, 2, 3, 4, 5, 6]  # Define numbers to print

    steps:
      - name: Print number
        run: echo "Number ${{ matrix.number }}"
