name: terraform

on: [push, workflow_dispatch]

jobs:
  terraform_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.9.7"
        
    - run: terraform init

    - name: Terraform Plan
      id: plan
      run: terraform plan

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve
      if: github.ref == 'refs/heads/main'
