name: terraform

on: 
  push:
  workflow_dispatch:
    inputs:
      apply_confirmation:
        description: 'Confirm to run terraform apply'
        required: true
        type: choice
        options:
          - "yes"
          - "no"
        default: "no"

jobs:
  terraform_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.9.7"

    - run: aws sts get-caller-identity
      
    - name: Configure AWS via Role Assumption
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::530694037299:role/github-runner-arc-test-role
        aws-region: 'us-east-1'
        
    - run: terraform init

    - name: Terraform Plan
      id: plan
      run: terraform plan

    - name: Terraform Apply
      if: ${{ github.event.inputs.apply_confirmation == 'yes' }}
      run: terraform apply -auto-approve
      # if: github.ref == 'refs/heads/main'
